directories/urls.py
from django.conf.urls import url, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index),

    # YellowPagesScraper,
    url(r'^scrape/(?P<source>\w{1,50})/(?P<search_terms>[+\w]+)/(?P<city>[-\w]+)/(?P<state>[-\w]+)/(?P<page_range>[0-9]{4})/(?P<password>[-\w]+)/$', views.scrape),
        ]

service_directory/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.signup),
    url(r'^buy/$', views.mediakit),
    url(r'^test/$', views.home_page),
    url(r'', include('directories.urls')),
    url(r'', include('tolearn.urls')),
    url(r'', include('angular_directory.urls')),
]

tolearn/urls.py
from django.conf.urls import url, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^learn', views.index),

        ]

directories/models.py
from django.db import models

from django.utils import timezone

class Dentist(models.Model):

    # name of office
    name=models.CharField(max_length=100)

    # City, state tuple in format: (HOU, TX)
    location=models.CharField(max_length=9, blank=True, null=True)

    # Category searched for in yellowpage scraper
    yp_category=models.CharField(max_length=100, null=True, blank=True)

    # Dict of subcategories and other misc fields important for search filtering
    search_tree=models.TextField(null=True, blank=True)
    email_data=models.TextField(null=True, blank=True)
    # subcategory from yellowpages
    yp_sub_category=models.CharField(max_length=5000, null=True, blank=True)
    insurance=models.CharField(max_length=512, null=True)
    phone=models.CharField(max_length=20, null=True)
    yp_street_address=models.CharField(max_length=100, blank=True, null=True)
    yp_city=models.CharField(max_length=30, blank=True, null=True)
    yp_state=models.CharField(max_length=3, blank=True, null=True)
    yp_zip_code=models.CharField(max_length=6, blank=True, null=True)

    # logo/image provided
    yp_image=models.CharField(max_length=256, blank=True, null=True)

    # description of company (dentist) on manta
    yp_description=models.TextField(blank=True, null=True)
    yp_email=models.TextField(blank=True, null=True)
    yp_extra_info=models.TextField(blank=True, null=True)
    # keywords associated with this dentist, provided by Manta.com
    yp_product_terms=models.TextField(max_length=512, blank=True, null=True)
    yp_url=models.CharField(max_length=512, blank=True, null=True)
    unionreporters_description=models.TextField(blank=True, null=True)
    current_dentists=models.TextField(blank=True, null=True)
    facebook_url=models.CharField(max_length=256, blank=True, null=True)
    twitter_url=models.CharField(max_length=256, blank=True, null=True)


    # TODO: replace unionreporters_raw_address with individual columns below it by parsing it
    unionreporters_raw_address = models.CharField(max_length=1024, blank=True, null=True)
    # unionreporters_street_address=models.CharField(max_length=100)
    # unionreporters_city=models.CharField(max_length=100)
    # unionreporters_state=models.CharField(max_length=100)
    # unionreporters_zip=models.CharField(max_length=100)

    unionreporters_location=models.CharField(max_length=512, blank=True, null=True)
    unionreporters_categories=models.TextField(blank=True, null=True)
    unionreporters_url=models.CharField(max_length=512, blank=True, null=True)

    unionreporters_phone=models.CharField(max_length=10, blank=True, null=True)


class Lead(models.Model):
    class Meta:
        db_table = '_leads'

    LEAD_TYPE_CHOICES = (
        ('company', 'Company'),
        ('person', 'Person'),
        )
    DATA_TYPE_CHOICES = (
        ('source', 'Source'),
        ('behavior', 'Behavior'),
        ('meta', 'Meta'),
    )
    lead_type=models.CharField(max_length=50, choices=LEAD_TYPE_CHOICES)
    data_type=models.CharField(max_length=50, choices=DATA_TYPE_CHOICES)
    data_table=models.CharField(max_length=100)
    data_table_fk=models.BigIntegerField()
    lead_name=models.CharField(max_length=512)


class ScrapeYellowpagesRecord(models.Model):
    class Meta:
        db_table = '_source_scrape_yellowpages'

    name=models.CharField(max_length=256)
    date_created = models.DateTimeField(default=timezone.now)
    unique_id = models.CharField(max_length=100, null=True)
    universal_citystate=models.CharField(max_length=100)
    street_address=models.CharField(max_length=256)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    zip_code=models.CharField(max_length=100)
    description=models.CharField(max_length=1024)
    email=models.CharField(max_length=100)
    phone=models.CharField(max_length=25)
    search_terms=models.CharField(max_length=200)
    extra_info=models.CharField(max_length=200, blank=True, null=True)
    url=models.CharField(max_length=200)
    product_terms=models.CharField(max_length=1024)


    def __str__(self):
        return self.unique_id


# class ScrapeSourceRecord():
#
#     def __init__(self, source, meta_info):
#         self.source = source
#         self.meta_info = meta_info
#
#
#     def run_scraper(self):
#
#         process = CrawlerRunner({
#             'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
#         })
#
#         if self.source == 'yellowpages':
#             print("works")
#             try:
#                 process.crawl(YellowPagesSpider)
#                 process.stop()
#             except Exception as err:
#                 print(err)
#
#         reactor.run()



# Scrapes yellowpages given search terms and location as parameters
# class YellowPagesSpider(scrapy.Spider):
#     name = "yellow_pages"
#     def __init__(self, *args, **kwargs):
#         super(YellowPagesSpider, self).__init__(*args, **kwargs)
#         self.meta_info = kwargs.get('meta_info')
#
#     def start_requests(self):
#
#         url = 'https://www.yellowpages.com/search?search_terms=' + self.meta_info['search_terms'] + \
#                 '&geo_location_terms=' + self.meta_info['city'] + '%2C+' + self.meta_info['state'] + '&page=3'
#
#             # url = 'https://www.yellowpages.com/search?search_terms=Dentist&geo_location_terms=Phoenix%2C+AZ&page=' + str(self.page_id)
#         yield scrapy.Request(url=url, callback=self.parse_results)
#
#
#     def parse_results(self, response):
#         url_list = []
#         for dentist in response.css('div.search-results div.result'):
#             url_list.append("https://www.yellowpages.com" + dentist.xpath('.//a[@class="business-name"]/@href').extract_first())
#         for url in url_list:
#
#             yield scrapy.Request(url=url, callback=self.parse_listing, meta={'url': url})

            # yield {
            #     'business' : dentist.xpath('.//span[@itemprop="name"]/text()').extract_first(),
            #     'street-address': dentist.xpath('.//span[@itemprop="streetAddress"]/text()').extract_first(),
            #     'phone': dentist.xpath('.//div[@itemprop="telephone"]/text()').extract_first(),
            #     'url': url,
            # }
    def parse_listing(self, response):
        listing_url = response.meta.get('url')

        yield {
            'yp listing url' : listing_url,
            'category' : 'Dentist',
            'business name': response.xpath('//div[@class="sales-info"]/h1/text()').extract(),
            'street': response.xpath('//p[@class="address"]/span/text()').extract_first(),
            'city': response.xpath('//p[@class="address"]').css('span:nth-child(2)::text').extract_first(),
            'state': response.xpath('//p[@class="address"]').css('span:nth-child(3)::text').extract_first(),
            'zip': response.xpath('//p[@class="address"]').css('span:nth-child(4)::text').extract_first(),
            'phone': response.xpath('//p[@class="phone"]/text()').extract_first(),
            'accepted insurance': response.xpath('//article[@id="accepted-insurance"]/p/text()').extract_first(),
            'extra': response.xpath('//dd[@class="other-information"]/p/text()').extract(),
            'email': response.xpath('//a[@class="email-business"]/@href').extract()
            # 'image': response.xpath('//a[@class="media-thumbnail"]/img/@src').extract_first(),
        }

# class SourcePhoneInbound(Lead):
#     pass

# class SourcePhoneOutbound(Lead):
#     pass

# class SiteSubmission(Lead):
#     pass

directories/forms.py
from django import forms
from directories.choices import *
import psycopg2


# Search form with only one universal search bar
class InitialSearchForm(forms.Form):




    search_terms = forms.CharField( max_length=400, required=False, widget=forms.TextInput(attrs={'placeholder': 'Optional keywords...'}))
    category = forms.ChoiceField(choices=CATEGORIES, required=True)
    location = forms.ChoiceField(choices=LOCATIONS, required=True)
    # DENTAL
    insurance = forms.ChoiceField(choices=HEALTH_INSURANCE_COMPANIES, required=False)

    # CONTRACTORS
    contractor_category = forms.ChoiceField(choices=CONTRACTOR_CATEGORIES, required=False)

    

# UNUSED
class DentistSearchForm(forms.Form):
    insurance = forms.ChoiceField(choices=HEALTH_INSURANCE_COMPANIES)

directories/views.py
from django.shortcuts import render, HttpResponse
from directories.models import Dentist
from .forms import InitialSearchForm, DentistSearchForm
from .utility import Search, Stack
from django.db.models import Q
from ast import literal_eval
import queue

from uuid import uuid4
from urllib.parse import urlparse
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.views.decorators.http import require_POST, require_http_methods
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from scrapyd_api import ScrapydAPI


scrapyd = ScrapydAPI('http://127.0.0.1:6800')

# takes search category as argument, returns list of form field keys associated with given category
def sub_category_switcher(category):
    switcher = {
        'Contractor' : ['contractor_category'],
        'Dentist' : ['insurance'],
        'Lawyer' : ['None'],
        'Restaurant' : ['None'],
        
    }
    return switcher.get(category)


# url: /
# homepage of bizzkinect.com
# handles search form and search results
def index(request):
    result = Dentist.objects.all()  # grab all listings
    form = InitialSearchForm(request.POST)  # Grabs (submitted) form data

    # if recieves a POST request, that means the form has been submitted,
    # and the data must be processed
    if request.method == 'POST':

        # Checks if form is valid, allows you to use form.cleaned_data
        # which checks for malicious submissions, incorrect submissions,
        # incorrectly formatted submissions, ensures requred fields aren't blank, etc.
        if form.is_valid():
            search_terms = form.cleaned_data['search_terms']
            category = form.cleaned_data['category']
            location = form.cleaned_data['location']
            # If search is empty
            if form.cleaned_data['search_terms'] != '':


            # sets search variable equal to the result set of the search query
                search = Dentist.objects.filter(
                    (Q(location__icontains=location) &
                    Q(yp_category__icontains=category)) &
                    (Q(name__icontains=search_terms) |
                    Q(yp_city__icontains=search_terms) |
                    Q(yp_extra_info__icontains=search_terms) |
                    Q(yp_category__icontains=search_terms) |
                    Q(search_tree__icontains=search_terms)) 
                )[:6]
            else:

                search = Dentist.objects.filter(
                    Q(location__icontains=location) &
                    Q(yp_category__icontains=category)
                )[:6]


            # dict to be returned in render response
            context = {
                'search': search,
                'form': InitialSearchForm(),
                'dentist_search_results': True,
            }
            # returns search_results page with context from above (search results, new blank form)
            return render(request, 'directories/index.html', context)
    else:

        form = InitialSearchForm()

        # returns empty form on first page load
    return render(request, 'directories/index.html', {'form': form,  'initial_search': True})

# Scrapy yellowpages
# /scrape/<source>/<search_terms>/<city>/<state>
@csrf_exempt
def scrape(request, source, search_terms, city, state, page_range, password):
    if password == 'am_ghey':
        meta_info = {

            "source": source,
            "search_terms": search_terms,
            "city": city,
            "state": state
        }

        # Unique ID for each scraper instance
        unique_id = str(uuid4())

        #Universally recognized citystate string
        universal_citystate = meta_info['city'] +'-' + meta_info['state']

        # Can be accessed from anywhere in scraper
        settings = {
            'universal_citystate': universal_citystate,
            'unique_id': unique_id,  # unique ID for each record for DB
            'USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
        }
        for page_counter in range(int(page_range)):
            
            # schedule Scrapyd task
            task = scrapyd.schedule('default', 'yellow_pages_spider', settings=settings, city=meta_info['city'], state=meta_info['state'], search_terms=meta_info['search_terms'], page_counter=page_counter)
        return JsonResponse({'task_id': task, 'unique_id': unique_id, 'universal_citystate': universal_citystate, 'status': 'started'})
    elif password == 'sboj':
        jobs = scrapyd.list_jobs('default')
        return HttpResponse(jobs['running'])
    else:
        return HttpResponse("Bad Password")


# # /vendor/create/$userid
# # create new vendor user
# # takes TS User object
# def create_vendor(request):

# # /vendor/update/$userid
# # update vendor user
# # takes TS User Object
# def update_vendor(request):

# #/vendor/delete/$userid
# # delete vendor user
# # Takes TS User object
# def delete_vendor(request):

# # /vendor/get/$userid
# # return vendor user
# # returns TS User object
# def get_vendors(request):

templates/directories/coming_soon.html
<div>Coming soon</div>

templates/directories/dentist_search_results.html
{#{% include "directories/home_page.html" %}#}
{% load static %}


<div style="margin-top:25px;" class="container" id="search_results_container">
    <div class="row" style="height:50px;">

        <a style="float:right;margin: 3px 3px 0 0;" href="/">
            <img height="50px" width="50px"
                 src="{% static "/images/orangex.png" %}">
        </a>
    </div>
    <div id="results">
        <ul style="list-style:none;">
            {% if search %}
                {% for result in search %}
                    {% if forloop.counter == 1 or forloop.counter == 3 or forloop.counter == 5 %}
                        <div class="row">
                    {% endif %}
                <div class="col-lg-6 col-md-6">

                    <li class="result" id="result-{{ forloop.counter }}">

                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <span id="result-title-{{ forloop.counter }}"
                                            class="result-title">{{ result.name }}</span>
                            </div>

                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <span id="address">{{ result.yp_street_address }} {{ result.yp_city }} {{ result.yp_state }} {{ results.yp_zip_code }}</span>
                            </div>

                        </div>
                        <div style="margin-top:20px" id="contact-us-{{ forloop.counter }}"class="row contact-us">
                        <div>
                            <span style="text-decoration:underline;"><strong>Book an appointment:</strong></span>
    </div>
                            <br/>
                            <span id="phone-number">{{ result.phone }}</span>
                            <br/>
                            <a href="{{ result.yp_url }}">Click here for more info!</a>
                        </div>
                        <div>

                        </div>


                        </br>
                    </li>

                </div>
                {% if forloop.counter == 2 or forloop.counter == 4 or forloop.counter == 6 %}
                    </div>
                {% endif %}

                {% endfor %}
                {% else %}
                <h1>0 RESULTS, PLEASE TRY A BROADER SEARCH</h1>
                {% endif %}
            

        </ul>
    </div>
</div>

templates/directories/footer.html
<h1>Footer</h1>

templates/directories/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Header</title>
</head>
<body>
    <h1 id="site-header" style="text-align:center; color:#ff9933;">Welcome. Why are you here?</h1>
<div class="container" id="header">
<ul class="nav nav-pills">
  <li role="presentation" ><a href="/learn">TO LEARN</a></li>
  <li role="presentation"><a href="/buy">TO BUY</a></li>
  <li role="presentation" ><a href="/signup">TO SIGNUP</a></li>
    <li role="presentation" ><a href="/login">TO LOGIN</a></li>
</ul>

{#    <div class="row" id="header-links">#}
{#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
{#            <a href="/learn">TO LEARN</a>#}
{#        </div>#}
{#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
{#            <a href="/buy">TO BUY</a>#}
{#        </div>#}
{#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
{#            <a href="/signup">TO SIGN UP</a>#}
{#        </div>#}
{#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
{#            <a href="/login">TO LOGIN</a>#}
{#        </div>#}
{#    </div>#}
</div>
</body>
</html>

templates/directories/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BizzKinect</title>
    <script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.3.1.min.js">
    </script>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Montserrat:400,500,600,600i,700,700i|Oswald:400,500,600"
          rel="stylesheet">
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">#}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <style>
        {#        @media (min-width: 992px) {#}
        {#            .navbar-toggleable-md .navbar-collapse {#}
        {#                display: -webkit-box !important;#}
        {#                display: -webkit-flex !important;#}
        {#                display: -ms-flexbox !important;#}
        {#                display: flex !important;#}
        {#                width: 100%;#}
        {#            }#}
        {#        }#}
        {##}
        {#                @media (min-width: 992px) {#}
        {#            .navbar-toggleable-md .navbar-nav {#}
        {#                flex-direction:row;#}
        {#            }#}
        {#        }#}
        form {
            margin: auto;
            width: 20%;
        }
        body {
            background: url('/static/images/blue-abstract-background.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            font-size: 24px;
        }
        @media (min-width: 768px) {
            .nav {
                float: none;
                margin: 0 auto;
                display: table;
                table-layout: fixed;
            }
            .wrapper {
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0;
                margin: auto;
            }
            #title-logo {
                width: 240px;
                position: absolute;
                top: 0;
                bottom: 125px;
                left: 0;
                right: 0;
                margin: auto;
            }
            #field-background {
                background-color: white;
                width: 360px;
                height: 34px;
                border-radius: 5px;
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0;
                margin: auto;
            }
        }
        ul.nav li {
            background-color: white;
            border-radius: 2px;
        }
        #header {
            margin-top: 20px;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
            font-style: italic;
        }
        h1#site-header {
            text-shadow: 2px 2px 2px red;
            font-size: 2.5em;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
        }
        #header-links {
            margin-top: 60px;
            font-size: 1em;
        }
        #header-links a {
            background-color: white;
            padding: 15px;
            border: 1px solid #ff9933;
            border-radius: 8px;
            color: #ff9933;
            opacity: .85;
        }
        #header-links a:hover {
            box-shadow: 2px 0 3px #ff9933;
            text-decoration: none !important;
            opacity: 1;
        }
        #title-logo {
            width: 240px;
        {#            position: absolute;#}{#            top: 0;#}{#            bottom: 125px;#}{#            left: 0;#}{#            right: 0;#}{##} margin: auto;
        }
        .center {
            margin: 0 auto;
            width: 240px;
        }
        .wrapper {
            width: 45%;
            height: 300px;
            border-radius: 7px;
        {#            position: absolute;#}{#            top: 0;#}{#            bottom: 0;#}{#            left: 0;#}{#            right: 0;#}{##}{#            margin: auto;#}{#            border: 2px solid white;#}{#            background-color: gray;#}
        }
        #crumbs {
            margin: 0 auto;
            width: 40%;
            position: absolute;
            top: 110px;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
        }
        .blue select {
            color: #000;
        }
        .slate select {
            color: #000;
        }
        .slate {
            background-color: #ddd;
        }
        .styled-select {
            background: url(http://i62.tinypic.com/15xvbd5.png) no-repeat 96% 0;
            border-radius: 5px;
            height: 29px;
            overflow: hidden;
        {#            width: 240px;#} width: 360px;
            font-size: 0.8em;
        }
        .styled-select select {
            background: transparent;
            border: none;
            border-radius: 5px;
            font-size: 14px;
            height: 29px;
            padding: 5px; /* If you add too much padding here, the options won't show in IE */
        {#            width: 268px;#} width: 400px;
        }
        .styled-select.slate {
            background: url(http://i62.tinypic.com/2e3ybe1.jpg) no-repeat right center;
            height: 34px;
        {#            width: 240px;#} width: 360px;
            border-radius: 5px;
        }
        .styled-select.slate select {
            border: 1px solid #ccc;
            font-size: 16px;
            height: 34px;
        {#            width: 268px;#} width: 400px;
            border-radius: 5px;
        }
        #field-background {
            background-color: white;
            width: 360px;
            height: 34px;
            border-radius: 5px;
        {#            position: absolute;#}{#            top: 0;#}{#            bottom: 0;#}{#            left: 0;#}{#            right: 0;#} margin: auto;
        }
        #submit-btn {
            border-radius: 5px;
            background-color: white;
            color: #5987a6;
            box-shadow: 2px 2px 2px gray;
            border: none;
            margin-left: 4px;
            height: 34px;
            width: 75px;
            font-size: 0.8em;
        }
        #id_search_terms {
            margin: 5px 0;
            width: 270px;
            height: 34px;
            border-radius: 5px;
            border: none;
            padding: 5px;
            box-shadow: 2px 2px 2px gray;
            font-size: 0.8em;
        }
        #category {
            background-color:white;
            margin-top:5px;
        }
        #contractor-form,
        #dental-form
        {
            background-color: white;
            margin: 7px auto;
        }
        .dynamic-form {
            width: 360px;
        }
        #search_results_container {
            border: 2px solid black;
            border-radius: 20px;
            background-color: white;
        }
        .result {
        {#                    background-color:gray; #} margin: 5px;
            border-radius: 7px;
            height: 275px;
        }
        span.result-title {
            font-size: 0.9em;
            font-family: 'Montserrat', sans-serif;
            font-style: italic;
        }
        span#address {
            font-size: 0.7em;
            font-family: 'Montserrat', sans-serif;
            font-style: italic;
        }
        #results {
            margin: auto;
            text-align: center;
            width: 90%;
        }
        .result {
            box-shadow: 4px 4px 4px gray;
        }
        #result-1 {
            border: 4px solid red;
            text-decoration-color: red;
        }
        #contact-us-1 {
            border: 3px solid red;
        }
        #result-2 {
            border: 4px solid green;
        }
        #contact-us-2 {
            border: 3px solid green;
        }
        #result-3 {
            border: 4px solid yellow;
        }
        #contact-us-3 {
            border: 3px solid yellow;
        }
        #result-4 {
            border: 4px solid blue;
        }
        #contact-us-4 {
            border: 3px solid blue;
        }
        #result-5 {
            border: 4px solid orange;
        }
        #contact-us-5 {
            border: 3px solid orange;
        }
        #result-6 {
            border: 4px solid purple;
        }
        #contact-us-6 {
            border: 3px solid purple;
        }
        #address {
            font-size: 0.7em;
        }
        .contact-us {
            padding: 5px;
            width: 75%;
            background-color: #e6e6e6;
            line-height: 1.5;
            margin-left: auto;
            margin-right: auto;
            border-radius: 4px;
            box-shadow: 3px 3px 3px gray;
        }
    </style>


</head>
<body>

{% load static %}


<h1 id="site-header" style="text-align:center; color:white;">Welcome, why are you here?</h1>
<div class="container" id="header">
    <ul class="nav nav-pills">
        <li role="presentation"><a href="/learn">TO LEARN</a></li>
        <li role="presentation"><a href="/buy">TO BUY</a></li>
        <li role="presentation"><a href="/signup">TO SIGNUP</a></li>
        <li role="presentation"><a href="/login">TO LOGIN</a></li>
    </ul>

    {#    <div class="row" id="header-links">#}
    {#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
    {#            <a href="/learn">TO LEARN</a>#}
    {#        </div>#}
    {#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
    {#            <a href="/buy">TO BUY</a>#}
    {#        </div>#}
    {#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
    {#            <a href="/signup">TO SIGN UP</a>#}
    {#        </div>#}
    {#        <div class="col-xs-3 col-lg-3 col-md-3 col-sm-3">#}
    {#            <a href="/login">TO LOGIN</a>#}
    {#        </div>#}
    {#    </div>#}
</div>

{% if initial_search %}
    {% include "directories/search.html" %}
{% endif %}


{% if dentist_search_results %}
    {% include "directories/dentist_search_results.html" %}
{% endif %}

<script>
    // $('div #dental-form').hide();
    // $('div #contractor-form').hide();
    // $('#id_category').on('change', function () {
    //     $('div#dental-form').hide();
    //     $('div#contractor-form').hide();
    //     var category = $("#id_category").val();
    //     switch (category) {
    //         case '1':
    //             console.log('break');
    //             break;
    //         case 'Contractor':
    //             $('div.dynamic-form').append("<div id=\"contractor-form\" class=\"styled-select slate\">" + "{{ form.contractor_category|escapejs }}" + "</div>");
    //             break;
    //         case 'Dentist':
    //             $('div.dynamic-form').append("<div id=\"dental-form\" class=\"styled-select slate\">" + "{{ form.insurance|escapejs }}" + "</div>");
    //             break;
    //         case 'Law':
    //             break;
    //         case 'Real Estate':
    //             break;
    //     }
    // });

</script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
</body>
</html>